---
title: "Expected Outcomes"
author: "Jules Tucher"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
```

## Expected Outcome Data

Build fake data.

```{r data}
# create sample groups
sample_df <- data.frame(
  participant_id = c(1:250),
  exposure = c(rep("control", 84), rep("credible", 83), rep("non-credible", 83))
  )

# create random outcome data
outcome_df <- sample_df %>%
  rowwise() %>%
  mutate(prior_belief = runif(1, 0, 1)) %>%
  mutate(prior_belief_cat = case_when(
    prior_belief < 0.4 ~ "pro-trans",
    prior_belief < 0.6 ~ "neutral", 
    TRUE ~ "anti-trans"
  )) %>%
  mutate(support_ban = case_when(
    exposure == "credible" & prior_belief_cat == "neutral" ~ prior_belief - runif(1, 0.1, 0.3),
    exposure == "non-credible" & prior_belief_cat == "neutral" ~ prior_belief - runif(1, 0.0, 0.2),
    TRUE ~ prior_belief
    ))

# collapse to group-level analysis dataset
results_df <- outcome_df %>%
  group_by(exposure, prior_belief_cat) %>%
  summarize(avg_support_ban = mean(support_ban),
            sd_support_ban = sd(support_ban),
            avg_prior_belief = mean(prior_belief),
            sd_prior_belief = sd(prior_belief))
```

## Expected Outcome Plots

Render plots.

```{r pressure, echo=FALSE}
jpeg("exposure_impacts_support.jpeg", 6, 4, units="in", res=300)
# Support for bans
results_df %>%
  ggplot() +
  geom_pointrange(aes(x = exposure,
                      y = avg_support_ban,
                      ymin = avg_support_ban - sd_support_ban,
                      ymax = avg_support_ban + sd_support_ban,
                      color = prior_belief_cat)
                  ) + 
  scale_color_manual(values = c("#212721", "#881c1c", "#ffc72c"),
                     name = "Prior Belief",
                     labels = c("Anti-Trans", "Neutral", "Pro-Trans")) +
  scale_x_discrete(labels = c("Control", "Credible", "Non-credible")) + 
  labs(x = "", y = "Support for GAC Ban")
dev.off()

png("beliefs_impact_support.png", 400, 400)
results_df %>%
  ggplot() +
  geom_pointrange(aes(x = prior_belief_cat,
                      y = avg_support_ban,
                      ymin = avg_support_ban - sd_support_ban,
                      ymax = avg_support_ban + sd_support_ban,
                      color = exposure)
                  ) + 
  scale_color_manual(values = c("#212721", "#881c1c", "#ffc72c"),
                     name = "Source Credibility",
                     labels = c("Control", "Credible", "Non-credible")) +
  scale_x_discrete(labels = c("Anti-Trans", "Neutral", "Pro-Trans")) + 
  labs(x = "", y = "Support for GAC Ban")
dev.off()

# Impact of prior beliefs on beliefs
# results_df %>%
#   pivot_longer(avg_support_ban:sd_prior_belief,
#                names_to = c("stat", "test"),
#                names_sep = "_") %>%
#   pivot_wider(id_cols = all_of(c("exposure", "test")), names_from = stat) %>%
#   ggplot() +
#   geom_pointrange(aes(x = test,
#                       y = avg,
#                       ymin = avg - sd,
#                       ymax = avg + sd,
#                       color = exposure)
#                   ) + 
#   scale_color_manual(values = c("#212721", "#881c1c", "#ffc72c"),
#                      name = "Source Credibility",
#                      labels = c("Control", "Credible", "Non-credible")) +
#   scale_x_discrete(labels = c("Pre", "Post")) + 
#   labs(x = "", y = "Support for GAC Ban")
```

